version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app1
      - app2
      - app3
  postgres-db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: nikochea1997
      POSTGRES_DB: mingeso1
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
  app1:
    container_name: mingeso_monolitico1
    image: nicolasvh/mingeso_monolitico
    ports:
      - "8091:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/mingeso1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=nikochea1997
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db
  app2:
    container_name: mingeso_monolitico2
    image: nicolasvh/mingeso_monolitico
    ports:
      - "8092:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/mingeso1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=nikochea1997
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db
  app3:
    container_name: mingeso_monolitico3
    image: nicolasvh/mingeso_monolitico
    ports:
      - "8093:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/mingeso1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=nikochea1997
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db